### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by vcoutasso** [vcoutasso/AmiaMond#5]
- [x] Corrigir o bug que está fazendo o jogo travar ao tentar retornar ao menu inicial pressionando ESC.
- [x] Descobrir e corrigir o motivo do seg fault ao fechar o jogo.
- [x] Arrumar erros de entrar e sair com esc (algumas vezes) do jogo e entrar no instruções.
- [x] Tentar localizar se tem um erro no multiplayer, que não consegui encontrar mais, pois acredito que já está funcionando (erro de crash)
- [x] Implementar a animação dos bonequinhos
- [x] Implementar colisões
- [ ] Implementar colisões para os outros tipos de obstáculos
- [ ] Corrigir o bug na tela de seleção do numero de jogadores. As vezes o jogo começa com a quantidade errada de jogadores
